"""owner expenses and individual settlements

Revision ID: dce4f6a8b015
Revises: cbd3e5f7a904
Create Date: 2026-09-11 22:57:20.850800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce4f6a8b015'
down_revision: Union[str, Sequence[str], None] = 'cbd3e5f7a904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settlement_charge_policies',
    sa.Column('charge_type', sa.String(length=30), nullable=False),
    sa.Column('liquidable_to_owner', sa.Boolean(), nullable=False),
    sa.Column('included_in_management_fee_base', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('charge_type')
    )
    op.create_table('owner_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('selection', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('request_key', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status != 'closed' OR closed_at IS NOT NULL", name='ck_owner_settlement_closed'),
    sa.CheckConstraint("status IN ('draft','closed','cancelled')", name='ck_owner_settlement_status'),
    sa.CheckConstraint('period_end > period_start', name='ck_owner_settlement_period'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_owner_settlements_owner_id'), 'owner_settlements', ['owner_id'], unique=False)
    op.create_table('owner_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('account_snapshot', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('request_key', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_owner_payout_amount'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['owner_bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['owner_settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_owner_payouts_settlement_id'), 'owner_payouts', ['settlement_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('supplier', sa.String(length=180), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('withholding_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('borne_by', sa.String(length=15), nullable=False),
    sa.Column('lifecycle', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("borne_by IN ('owner','manager','tenant','other')", name='ck_expense_bearer'),
    sa.CheckConstraint("lifecycle IN ('posted','void')", name='ck_expense_lifecycle'),
    sa.CheckConstraint('total_amount > 0 AND base_amount >= 0 AND vat_amount >= 0 AND withholding_amount >= 0', name='ck_expense_money'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 100 AND withholding_rate >= 0 AND withholding_rate <= 100', name='ck_expense_tax'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_property_id'), 'expenses', ['property_id'], unique=False)
    op.create_table('management_fee_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('fee_type', sa.String(length=40), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("fee_type = 'percentage_on_collected'", name='ck_management_fee_type'),
    sa.CheckConstraint('effective_until IS NULL OR effective_until > effective_from', name='ck_management_fee_dates'),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_management_fee_percentage'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 100 AND withholding_rate >= 0 AND withholding_rate <= 100', name='ck_management_fee_tax'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_fee_terms_owner_id'), 'management_fee_terms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_management_fee_terms_property_id'), 'management_fee_terms', ['property_id'], unique=False)
    op.create_table('expense_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('paid_by', sa.String(length=12), nullable=False),
    sa.Column('paid_by_owner_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrects_id', sa.Integer(), nullable=True),
    sa.Column('request_key', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(direction = 'reversal' AND corrects_id IS NOT NULL) OR (direction = 'payment' AND corrects_id IS NULL)", name='ck_expense_payment_correction'),
    sa.CheckConstraint("(paid_by = 'owner' AND paid_by_owner_id IS NOT NULL) OR (paid_by != 'owner' AND paid_by_owner_id IS NULL)", name='ck_expense_payment_owner'),
    sa.CheckConstraint("direction IN ('payment','reversal')", name='ck_expense_payment_direction'),
    sa.CheckConstraint("paid_by IN ('manager','owner','other')", name='ck_expense_payment_actor'),
    sa.CheckConstraint('amount > 0', name='ck_expense_payment_amount'),
    sa.ForeignKeyConstraint(['corrects_id'], ['expense_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paid_by_owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_expense_payments_expense_id'), 'expense_payments', ['expense_id'], unique=False)
    op.create_table('payment_custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(actor = 'owner' AND owner_id IS NOT NULL) OR (actor = 'manager' AND owner_id IS NULL)", name='ck_payment_custody_owner'),
    sa.CheckConstraint("actor IN ('manager','owner')", name='ck_payment_custody_actor'),
    sa.CheckConstraint('amount > 0', name='ck_payment_custody_amount'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['owner_bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_custody_payment_id'), 'payment_custody', ['payment_id'], unique=False)
    op.create_table('owner_settlement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('payment_allocation_id', sa.Integer(), nullable=True),
    sa.Column('expense_payment_id', sa.Integer(), nullable=True),
    sa.Column('prior_settlement_id', sa.Integer(), nullable=True),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('fee_terms_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.CheckConstraint("(kind = 'income' AND payment_allocation_id IS NOT NULL AND expense_payment_id IS NULL AND prior_settlement_id IS NULL) OR (kind = 'expense' AND payment_allocation_id IS NULL AND expense_payment_id IS NOT NULL AND prior_settlement_id IS NULL) OR (kind = 'prior_balance' AND payment_allocation_id IS NULL AND expense_payment_id IS NULL AND prior_settlement_id IS NOT NULL)", name='ck_owner_settlement_line_source'),
    sa.CheckConstraint("kind IN ('income','expense','prior_balance')", name='ck_owner_settlement_line_kind'),
    sa.ForeignKeyConstraint(['expense_payment_id'], ['expense_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fee_terms_id'], ['management_fee_terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ownership_id'], ['property_ownerships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_allocation_id'], ['payment_allocations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prior_settlement_id'], ['owner_settlements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['owner_settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_key', name='uq_owner_settlement_consumption')
    )
    op.create_index(op.f('ix_owner_settlement_lines_settlement_id'), 'owner_settlement_lines', ['settlement_id'], unique=False)
    categories = sa.table('expense_categories', sa.column('code'), sa.column('name'), sa.column('active'))
    op.bulk_insert(categories, [dict(code=code, name=name, active=True) for code, name in (
        ('cleaning', 'Limpieza'), ('repair', 'Reparación'), ('utilities', 'Suministros'),
        ('community', 'Comunidad'), ('insurance', 'Seguro'), ('tax', 'Impuestos / tasas'),
        ('maintenance', 'Mantenimiento'), ('other', 'Otros'))])
    policies = sa.table('settlement_charge_policies', sa.column('charge_type'),
                        sa.column('liquidable_to_owner'), sa.column('included_in_management_fee_base'))
    op.bulk_insert(policies, [dict(charge_type=kind, liquidable_to_owner=kind == 'rent',
                                   included_in_management_fee_base=kind == 'rent') for kind in
        ('rent', 'security_deposit', 'reservation_deposit', 'utilities', 'extraordinary', 'discount', 'deposit_retention')])
    # Immutable documentary history. No trigger changes any business data.
    for table in ('owner_settlement_lines', 'owner_payouts', 'expense_payments'):
        for action in ('UPDATE', 'DELETE'):
            op.execute(f"CREATE TRIGGER {table}_immutable_{action.lower()} BEFORE {action} ON {table} "
                       "BEGIN SELECT RAISE(ABORT, 'Financial history is immutable'); END")
    for action in ('UPDATE', 'DELETE'):
        op.execute(f"CREATE TRIGGER owner_settlements_closed_{action.lower()} BEFORE {action} ON owner_settlements "
                   "WHEN OLD.status = 'closed' BEGIN SELECT RAISE(ABORT, 'Closed settlement is immutable'); END")


def downgrade() -> None:
    """Downgrade schema."""
    for table in ('expenses', 'expense_payments', 'management_fee_terms', 'owner_settlements', 'owner_payouts', 'payment_custody'):
        if op.get_bind().execute(sa.text(f'SELECT COUNT(*) FROM {table}')).scalar():
            raise RuntimeError('Conservar la actividad económica antes de retirar estas tablas.')
    op.drop_index(op.f('ix_owner_settlement_lines_settlement_id'), table_name='owner_settlement_lines')
    op.drop_table('owner_settlement_lines')
    op.drop_index(op.f('ix_payment_custody_payment_id'), table_name='payment_custody')
    op.drop_table('payment_custody')
    op.drop_index(op.f('ix_expense_payments_expense_id'), table_name='expense_payments')
    op.drop_table('expense_payments')
    op.drop_index(op.f('ix_management_fee_terms_property_id'), table_name='management_fee_terms')
    op.drop_index(op.f('ix_management_fee_terms_owner_id'), table_name='management_fee_terms')
    op.drop_table('management_fee_terms')
    op.drop_index(op.f('ix_expenses_property_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_owner_payouts_settlement_id'), table_name='owner_payouts')
    op.drop_table('owner_payouts')
    op.drop_index(op.f('ix_owner_settlements_owner_id'), table_name='owner_settlements')
    op.drop_table('owner_settlements')
    op.drop_table('settlement_charge_policies')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
